### ISSUE TITLE
Facebook integration

### ISSUE THREAD

**Issue by npotier** [lyrixx/lifestream#2]
Hi,

I've been looking for such a lib, which seem very interesting :)

Is there any reason why Facebook services are not coded yet ? Is this in your roadmap ? What do you think about it ?

I would be pleased to help and contribute.

Nicolas.

**Comment by lyrixx** [comment]
Oh, sorry. I totally missed your issue.
I had no plan to implement facebook, as I don't use facebook.

But If you implement it, I will be glad to merge it.

**Comment by lyrixx** [comment]
This lib is now deprecated. Sorry.
